

all: \
	10kb.test_topologies.out \
	100kb.test_topologies.out 



100kb.random_trees_ln: ../gf_trees/all_trees.100kb.tre
	sed 's/\:[0-9][\.]*[a-z0-9]*[-]*[0-9]*//g' $<  | fgrep -n $$(cat best_tree) | shuf -n 500  | cut -f1 -d ":" > $@ # get line numbers

10kb.random_trees_ln: ../gf_trees/all_trees.10kb.tre
	sed 's/\:[0-9][\.]*[a-z0-9]*[-]*[0-9]*//g' $<  | fgrep -n $$(cat best_tree) | shuf -n 500 | cut -f1 -d ":" > $@ # get line numbers


10kb.test_topologies.out: 10kb.random_trees_ln
	./test_topologies.sh $< ../10kb_fragments $@

100kb.test_topologies.out: 100kb.random_trees_ln
	./test_topologies.sh $< ../100kb_fragments $@

